version: '3.1'

services:
  test:
    container_name: test
    restart: always
    build: 
      context: .
      dockerfile: DockerfileTest
    links:
      - mongo_tests
    depends_on:
      - mongo_tests

  mongo_tests:
    container_name: mongo_tests
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - data_test:/data/db
    expose:
      - "27018"
    command: mongod --port 27018
    ports:
      - '27018:27018'

volumes:
  data_test:
